spring:
  datasource:
    url: jdbc:mysql://192.168.1.9:3306/DoctorAppointment
    username: mohammad
    password: myjava123
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true


security:
  jwt:
    secret-key: a459654cc535e86c3e4879347aabd02f305b40982a02abfb228def3250d1ad5b
    expiration-time: 3600000

server:
  port: 8080
springdoc:
  api-docs:
    path: /api-docs